### ISSUE TITLE
Most middleware is no longer bundled with Express and must be installed separately error

### ISSUE THREAD

**Issue by phrozen755** [smurthas/fitbit-js#15]
Looks like you need to update the example file, maybe rework a few things.

Full error:

```
development/fbit/example/node_modules/express/lib/express.js:99
      throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
      ^

Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately.
```

**Comment by pbojinov** [comment]
@phrozen755 the express version he's most likely using is 3.x.x whereas if you ran `npm install express` at the moment it will give you 4.x.x. 

Try running `npm install express@">=3.0.0 <4.0.0" --save` from the example folder and it will resolve the error you're seeing.

**Comment by smurthas** [comment]
Thanks for answering the question @phrozen755. I've merged #13 and updated the example to use express 4.x.x.

I'm did a version bump and published to npm, so `v0.3.2` has the update included.

**Comment by pbojinov** [comment]
:+1:

**Comment by phrozen755** [comment]
Thanks gentlemen! :+1:

**Comment by ghost** [comment]
Thanks Gentle Man

**Comment by tejas-kr** [comment]
thanks man!

**Comment by the1thing** [comment]
Thanks 👍

**Comment by Nilesh-Misal** [comment]
Thanks, Gentlemen 👍

**Comment by kev5** [comment]
After coming down to an earlier version of express as suggested, I faced a new error-

```
router.get('/', function(req, res, next) {
       ^

TypeError: Cannot read property 'get' of undefined
```

**Comment by learnwithalfred** [comment]
express@">=3.0.0 <4.0.0"

run this 
it woked for me

**Comment by deevally** [comment]
> After coming down to an earlier version of express as suggested, I faced a new error-
> 
> ```
> router.get('/', function(req, res, next) {
>        ^
> 
> TypeError: Cannot read property 'get' of undefined
> ```

I have same issue right now and cannot fix it

**Comment by requireSol** [comment]
Got the Same Problem like geraldanosike :(

**Comment by Srinivasa9164** [comment]
Got same problem

**Comment by Srinivasa9164** [comment]
After I got this error

throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
      ^

Error: Most middleware (like methodOverride) is no longer bundled with Express and must be installed separately.

**Comment by kcsrinivasa** [comment]
After I got his error If I install the express greater than 4 version it is working but If I install 
npm install express@">=3.0.0 <4.0.0" --save I am getting following error

router.use('/ivr', twilio.webhook({validate: false}), ivrRouter);
       ^

TypeError: router.use is not a function

**Comment by PappuKP** [comment]
> @phrozen755 the version of express @smurthas is using in this example is 3.x.x, whereas if you run `npm install express` at the moment it will give you 4.x.x.
> 
> Try running `npm install express@">=3.0.0 <4.0.0" --save` from the example folder and it will resolve the error you're seeing.

thank you

**Comment by rahulkhichi199** [comment]
(connect deprecated limit: Restrict request size at location of read app.js:24:17)


it appears after that
then how to solve this error!!

**Comment by nupur1997** [comment]
Thank you so much its working now :)
